### ISSUE TITLE
FOUC (Flash Of Unkontexted Content) 

### ISSUE THREAD

**Issue by daanvanham** [konfirm/kontext#11]
When binding something (e.q. an array) to the DOM, there is a moment of FOUC (Flash Of Unkontexted Content). I don't think this is is fixable by kontext, but maybe setting an attribute (or className, but I prefer attribute) on the element on which the binding occurs, after binding is done, could help. One could then use said attribute/className to display the elements, so the user doesn't see the unbinded DOMNode.

**Comment by rspieker** [comment]
After some pondering there is now [a solution in place](https://github.com/konfirm/kontext/blob/master/dist/release-notes.md#fouc)

As the world appears to have different views on whether to prefer classes or other attributes, the default is now to remove a class that goes by the name 'unbound-kontext' from the elements targetted by the binding.

Any overrides can be provided to the `.bind` method or set as default, in order to have an attribute removed, the syntax is:
```
kontext.bind({hello: 'world'}, {after: {attribute: 'data-fouc', value: '-prevent'}});
```

Where the `-` in front of the value means: 'remove this value' (similarly a `+` means: 'add this value')
