### ISSUE TITLE
`each: {self: true}` does not resolve other extensions on itself

### ISSUE THREAD

**Issue by daanvanham** [konfirm/kontext#4]
When I have an node with a self-looping each extension and at least one other extension added through the `data-kontext` attribute, the other extensions are not being "executed".

e.q.:
Somewhere in my model
```
loop: [
   {name: 'test', unit: 'hi'},
   {name: 'another', unit: 'hello'}
]
```

HTML:
```
<li data-kontext="text: name, attr: {data-thing: unit}, each: {target: loop, self: true}"></li>
```

Renders:
```
<li></li>
<li></li>
```

Expected:
```
<li data-thing=hi>test</li>
<li data-thing=hello>another</li>
```

I'm not sure if this is by design or a "won't fix", but I caught myself trying this a couple of times, so for me it would be a nice feature!

**Comment by daanvanham** [comment]
Update: 
When the HTML uses a placeholder for `name` instead of the `text` extension, it renders the textNode.

```
<li data-kontext="attr: {data-thing: unit}, each: {target: loop, self: true}">{name}</li>
```

Renders:
```
<li>test</li>
<li>another</li>
```

**Comment by rspieker** [comment]
It was actually intended this way, mostly to prevent the `each: {self: true}` from recurring on every node. It just seemed more intuitive to remove the `data-kontext` attribute entirely.

Then again, I've found myself also adding more extension and wondering why it didn't work, so there is an issue, I'm just not sure what the proper solution would be.

At the moment I can come up with a couple of sane scenario's:
- preserve the `data-kontext` attribute, with the `each` part removed (this seems to be what you expected)
- remove the `data-kontext`attribute (this is the current flow), but make it more obvious other extensions won't be triggered (which is not entirely true)
- remove the feature and go back to the drawing board on how to have repeating elements without a parent element

My use case is to have definition lists `<dl>` where either or both the `<dt>` and `<dd>` elements can be repeated and they should be siblings.

I will leave the issue open until a proper solution can be implemented, or when it is decided the functionality should go.

**Comment by rspieker** [comment]
From commit 6144180 onwards the `each` declaration (regardless its name) will be removed from the `data-kontext` attribute (regardless its name) whilst preserving any other extension configuration.

There were two (major) concerns which needed to be addressed in order to make this change possible:
- it was impossible to know exactly what name was used for the extension, as it may have been abbreviated or even aliased.
- it was also impossible to know which attribute was used to configure the extension, as the default `data-kontext` can be configured to be any attribute.

After both of these concerns were addressed, the only thing remaining was to create the logic to remove only the `each: ...` portion from the attribute, this turned out to be rather simple as one can only add the `self: true` when using the object notation (`each: {target: X, self: true}`).

This notation in itself does not require any nested objects, so the _assumption_ can be made that the first closing curly after `each: {` will be the one ending the declaration.
